apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}

    spec:
      containers:
        - name: laptop-recommendation-agent

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: laptop-agent-secrets
                  key: OPENAI_API_KEY

            - name: API_URL
              value: {{ .Values.apiUrl | quote }}