apiVersion: v1
kind: Service

metadata:
  name: laptop-recommendation-agent-service

spec:
  type: NodePort

  selector:
    app: laptop-recommendation-agent

  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501