replicaCount: 1

image:
  repository: ghcr.io/tulasigudibanda/laptop-recommendation-agent
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8501
  targetPort: 8501

containerPort: 8501

apiUrl: "https://laptop-recommendation-agent.onrender.com"